In [4]:
# Creating Taining Set
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1



In [7]:
df

feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1

## Step-1: Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])
df.head(5)

feature1  feature2  feature3  target
0  0.473294  0.167622 -0.987345       1
1  0.724424  1.169350 -1.332261       1
2 -0.449148 -1.556529 -1.674155       1
3  1.458807 -0.385625  0.838706       1
4  0.165928  0.218801 -1.322635       1

## Step-2: Covariance Matrix

In [20]:
Cov_mat = np.cov( [ df.iloc[:,0],df.iloc[:,1],df.iloc[:,2] ] )
Cov_mat

array([[ 1.05263158,  0.20397591, -0.28888004],
       [ 0.20397591,  1.05263158,  0.10956124],
       [-0.28888004,  0.10956124,  1.05263158]])

## Step-3: Eigenval and Eigenvectors

In [21]:
eigenval,eigenvec = np.linalg.eig(Cov_mat)

In [22]:
eigenval

array([0.64212617, 1.36120658, 1.15456198])

In [23]:
eigenvec

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])

### Get Largest Values

In [24]:
PC_1_2 = eigenvec[1:]
PC_1_2

array([[ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])

## Step-4: Transform Data into Reduced Dimension

In [25]:
transpose_PC = PC_1_2.T
transpose_PC

array([[ 0.48046517, -0.58686326],
       [ 0.28140349, -0.60066414],
       [ 0.8306415 ,  0.54294945]])

In [29]:
Transformed = np.dot(df.iloc[:,:3],transpose_PC)

new_df = pd.DataFrame(Transformed,columns=['PC1','PC2'])
new_df['target'] = df['target'].values

new_df

PC1       PC2  target
0  -0.545559 -0.914522       1
1  -0.429512 -1.850875       1
2  -2.044435  0.289559       1
3   1.289053 -0.169115       1
4  -0.957342 -0.946927       1
5   0.906913  0.898292       1
6  -1.417818  1.649363       1
7   1.495777 -0.479971       1
8  -0.464117  0.618521       1
9  -0.693634 -1.665405       1
10  1.533499 -0.658939       1
11 -0.124367 -1.017623       1
12 -0.404657  1.585754       1
13  0.949148  0.630803       1
14  0.249784 -0.645396       1
15  0.288784 -0.977292       1
16 -0.564757  0.618717       1
17  0.405505 -0.475355       1
18 -0.201641  2.040791       1
19  0.729374  1.469620       1