In [150]:
import numpy as np
import matplotlib.pyplot as plt

<a name="toc_15456_2"></a>
# 2 Problem Statement

You will use the motivating example of housing price prediction. The training dataset contains three examples with four features (size, bedrooms, floors and, age) shown in the table below.  Note that, unlike the earlier labs, size is in sqft rather than 1000 sqft. This causes an issue, which you will solve in the next lab!

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  

You will build a linear regression model using these values so you can then predict the price for other houses. For example, a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old.  

Please run the following code cell to create your `X_train` and `y_train` variables.

In [151]:
X_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
Y_train = np.array([460,232,178])

In [152]:
X_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [153]:
Y_train

array([460, 232, 178])

In [154]:
b_init = 0
w_init = np.array([ 0,0,0,0])
alpha = 5.0e-7

In [155]:
def Cost_func(x,y,w,b):
    m = x.shape[0]
    costf = 0
    for i in range(len(x)):
        error = np.dot(w,x[i]) + b - y[i]
        costf+= pow(costf,2)

    return costf/(2*m)

In [156]:
def compute_gradient(X, y, w, b): 
    m,n = X.shape          
    dj_dw = np.zeros(n)
    dj_db = 0.

    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] += err * X[i][j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_db, dj_dw

In [157]:
def gradient_descent(X, y, w_in, b_in,alpha,): 
    
    for i in range(1000):
        dj_db,dj_dw = compute_gradient(X, y, w_in, b_in)   

        w_in = w_in - alpha * dj_dw              
        b_in = b_in - alpha * dj_db               
    
    return w_in, b_in 

In [158]:
w_f,b_f = gradient_descent(X_train,Y_train,w_init,b_init,alpha)
w_f

array([ 0.20396569,  0.00374919, -0.0112487 , -0.0658614 ])

In [159]:
b_f

-0.002235407530932535